FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build-env
WORKDIR /app

# Copy everything and build
# Copy csproj and restore as distinct layers
COPY ../Polaris.Contracts/ ./Polaris.Contracts/
COPY ../Polaris.Api/Polaris.Api.csproj ./Polaris.Api/
RUN dotnet restore Polaris.Api/Polaris.Api.csproj

# Copy everything else and build
COPY . ./
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:7.0
WORKDIR /app
COPY --from=build-env /app/out .

# Set the entrypoint to the web app's dll
ENTRYPOINT ["dotnet", "Polaris.Api.dll"]