version: '3'

services:
  polaris:
    build: 
      context: .
      dockerfile: ./Polaris.Api/dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=Polaris;User Id=sa;Password=YourStrongPassword123;TrustServerCertificate=True;MultipleActiveResultSets=true

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: YourStrongPassword123
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"

  polaris-ui:
    build: 
      context: .
      dockerfile: ./Polaris.Ui/dockerfile
    ports:
      - "5000:80"
    depends_on:
      - polaris
    environment:
      - PolarisApiUrl=http://polaris:80