FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY ../Polaris.Contracts/ ./Polaris.Contracts/
COPY ../Polaris.Ui/Polaris.Ui.csproj ./Polaris.Ui/
RUN dotnet restore Polaris.Ui/Polaris.Ui.csproj

# Copy everything else and build
COPY . ./
RUN dotnet publish -c Release -o out

# Runtime stage
FROM mcr.microsoft.com/dotnet/aspnet:7.0
WORKDIR /app
COPY --from=build /app/out .

# Set the environment variable for the API endpoint
ENV API_ENDPOINT=http://polaris-api:8080

# Expose port and start the UI
EXPOSE 80
ENTRYPOINT ["dotnet", "Polaris.Ui/Polaris.Ui.dll"]
